### ISSUE TITLE
Unity texture UV offsets not inherited

### ISSUE THREAD

**Issue by Rodg88** [KSPModdingLibs/Shabby#17]
These `tiling` and `offset` fields aren't inherited when using material replace
![image](https://github.com/user-attachments/assets/97644f56-11f3-47ba-8115-21fcaae743a9)

**Comment by drewcassidy** [comment]
is `updateExisting` true?

**Comment by Rodg88** [comment]
Yep, since thats the default value.

**Comment by drewcassidy** [comment]
this might actually be a Unity bug, try the last build

**Comment by Rodg88** [comment]
No change in the latest version

**Comment by drewcassidy** [comment]
Issue was caused by the shaders used
