### ISSUE TITLE
Assigning the texture to the channel

### ISSUE THREAD

**Issue by rockmeowstar** [KSPModdingLibs/Shabby#19]
Please add a compatibility to attach the texture to the particular channel, like in this scheme under the arrow. For now, we can define the texture but the result is not used because it's not attached to the channel (or I understand it really wrong). 
![01-5](https://github.com/user-attachments/assets/ebc92c6d-d46e-4d55-9b61-232db6dd8921)

**Comment by drewcassidy** [comment]
Looks like you’re wanting to make a shader? I have no idea what you’re asking for here

**Comment by rockmeowstar** [comment]
> Looks like you’re wanting to make a shader? I have no idea what you’re asking for here

Sorry, let me give you some context.
We have a stock model that needs retexturing. If we take the diffuse texture and replace it, everything works fine because the diffuse texture is already connected to the color and alpha channels.
Let's say I want to keep the stock color channel and reassign the alpha channel to my texture. But I can't do that because the only entities that are defined are vectors, values, and textures. Texture-shader links cannot be reassigned.

There are several stock models in the game with broken links between the alpha channel and gloss (it's a bug), and the easiest way to restore these links today is to edit and resave the model. I would like to get rid of this and be able to assign links inside the material like this:


```
SHABBY_MATERIAL_DEF
{
    name = CupolaGlossMaterial
    shader = KSP/Emissive/Bumped Specular

    TEXTURE
    	{
	_MainTex = Squad/Parts/Command/cupola/ksp_l_cupola_diff
	_Emissive = Squad/Parts/Command/cupola/cupola_Emissive
	_BumpMap = Squad/Parts/Command/cupola/ksp_l_cupola_normal
        _GlossTex = 000_ShineFix/Parts/Command/cupola/ksp_l_cupola_alpha
    	}
    LINKS
    	{
        _GlossTex.Alpha = _MainColor.TAlpha
        _MainColor.Alpha = StandardShader.Gloss
    	}
    COLOR
    	{
        _SpecColor = #e7e7e7
    	}
    FLOAT
    	{
        _Shininess = 0.593
    	}
}
```

For me, this seems like the most convenient option that I can do with the model without changing its principles or reworking it entirely.

**Comment by drewcassidy** [comment]
I still don’t understand how this would work without writing a new shader. You can’t just assign a texture to a single channel of another texture like that

**Comment by drewcassidy** [comment]
Closing as wontfix, the only way to implement this would be to modify textures in memory which is out of scope. Write a custom shader instead.
